// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfEventGetpwnam struct {
	Base struct {
		Pid    int32
		Comm   [16]int8
		Cpu    int32
		ErrMsg [32]int8
	}
	Result struct {
		PwName   [16]int8
		PwPasswd [16]int8
		PwUid    uint32
	}
	LookingName [16]int8
	Ret         int32
}

type bpfEventGetpwuid struct {
	Base struct {
		Pid    int32
		Comm   [16]int8
		Cpu    int32
		ErrMsg [32]int8
	}
	Result struct {
		PwName   [16]int8
		PwPasswd [16]int8
		PwUid    uint32
	}
	LookingUid uint32
	Ret        int32
}

type bpfEventOpenpty struct {
	Base struct {
		Pid    int32
		Comm   [16]int8
		Cpu    int32
		ErrMsg [32]int8
	}
}

type bpfEventPam struct {
	Base struct {
		Pid    int32
		Comm   [16]int8
		Cpu    int32
		ErrMsg [32]int8
	}
	ApiName     [16]int8
	ServiceName [16]int8
	User        [16]int8
	Authtok     [16]int8
	PamRet      int32
}

type bpfEventSyscallTraceEnter struct {
	Base struct {
		Pid    int32
		Comm   [16]int8
		Cpu    int32
		ErrMsg [32]int8
	}
	SyscallNum uint64
}

type bpfPtRegs struct {
	R15     uint64
	R14     uint64
	R13     uint64
	R12     uint64
	Rbp     uint64
	Rbx     uint64
	R11     uint64
	R10     uint64
	R9      uint64
	R8      uint64
	Rax     uint64
	Rcx     uint64
	Rdx     uint64
	Rsi     uint64
	Rdi     uint64
	OrigRax uint64
	Rip     uint64
	Cs      uint64
	Eflags  uint64
	Rsp     uint64
	Ss      uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	AfterGetpwnam           *ebpf.ProgramSpec `ebpf:"after_getpwnam"`
	AfterGetpwnamR          *ebpf.ProgramSpec `ebpf:"after_getpwnam_r"`
	AfterGetpwuid           *ebpf.ProgramSpec `ebpf:"after_getpwuid"`
	AfterGetpwuidR          *ebpf.ProgramSpec `ebpf:"after_getpwuid_r"`
	AfterOpenpty            *ebpf.ProgramSpec `ebpf:"after_openpty"`
	AfterPamAuthenticate    *ebpf.ProgramSpec `ebpf:"after_pam_authenticate"`
	BeforeGetpwnam          *ebpf.ProgramSpec `ebpf:"before_getpwnam"`
	BeforeGetpwnamR         *ebpf.ProgramSpec `ebpf:"before_getpwnam_r"`
	BeforeGetpwuid          *ebpf.ProgramSpec `ebpf:"before_getpwuid"`
	BeforeGetpwuidR         *ebpf.ProgramSpec `ebpf:"before_getpwuid_r"`
	BeforePamAuthenticate   *ebpf.ProgramSpec `ebpf:"before_pam_authenticate"`
	BeforeSyscallTraceEnter *ebpf.ProgramSpec `ebpf:"before_syscall_trace_enter"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	EventsGetpwnam          *ebpf.MapSpec `ebpf:"events_getpwnam"`
	EventsGetpwuid          *ebpf.MapSpec `ebpf:"events_getpwuid"`
	EventsOpenpty           *ebpf.MapSpec `ebpf:"events_openpty"`
	EventsPam               *ebpf.MapSpec `ebpf:"events_pam"`
	EventsSyscallTraceEnter *ebpf.MapSpec `ebpf:"events_syscall_trace_enter"`
	HashGetpwnam            *ebpf.MapSpec `ebpf:"hash_getpwnam"`
	HashGetpwnamR           *ebpf.MapSpec `ebpf:"hash_getpwnam_r"`
	HashGetpwuid            *ebpf.MapSpec `ebpf:"hash_getpwuid"`
	HashGetpwuidR           *ebpf.MapSpec `ebpf:"hash_getpwuid_r"`
	HashPamAuthenticate     *ebpf.MapSpec `ebpf:"hash_pam_authenticate"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	EventsGetpwnam          *ebpf.Map `ebpf:"events_getpwnam"`
	EventsGetpwuid          *ebpf.Map `ebpf:"events_getpwuid"`
	EventsOpenpty           *ebpf.Map `ebpf:"events_openpty"`
	EventsPam               *ebpf.Map `ebpf:"events_pam"`
	EventsSyscallTraceEnter *ebpf.Map `ebpf:"events_syscall_trace_enter"`
	HashGetpwnam            *ebpf.Map `ebpf:"hash_getpwnam"`
	HashGetpwnamR           *ebpf.Map `ebpf:"hash_getpwnam_r"`
	HashGetpwuid            *ebpf.Map `ebpf:"hash_getpwuid"`
	HashGetpwuidR           *ebpf.Map `ebpf:"hash_getpwuid_r"`
	HashPamAuthenticate     *ebpf.Map `ebpf:"hash_pam_authenticate"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.EventsGetpwnam,
		m.EventsGetpwuid,
		m.EventsOpenpty,
		m.EventsPam,
		m.EventsSyscallTraceEnter,
		m.HashGetpwnam,
		m.HashGetpwnamR,
		m.HashGetpwuid,
		m.HashGetpwuidR,
		m.HashPamAuthenticate,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	AfterGetpwnam           *ebpf.Program `ebpf:"after_getpwnam"`
	AfterGetpwnamR          *ebpf.Program `ebpf:"after_getpwnam_r"`
	AfterGetpwuid           *ebpf.Program `ebpf:"after_getpwuid"`
	AfterGetpwuidR          *ebpf.Program `ebpf:"after_getpwuid_r"`
	AfterOpenpty            *ebpf.Program `ebpf:"after_openpty"`
	AfterPamAuthenticate    *ebpf.Program `ebpf:"after_pam_authenticate"`
	BeforeGetpwnam          *ebpf.Program `ebpf:"before_getpwnam"`
	BeforeGetpwnamR         *ebpf.Program `ebpf:"before_getpwnam_r"`
	BeforeGetpwuid          *ebpf.Program `ebpf:"before_getpwuid"`
	BeforeGetpwuidR         *ebpf.Program `ebpf:"before_getpwuid_r"`
	BeforePamAuthenticate   *ebpf.Program `ebpf:"before_pam_authenticate"`
	BeforeSyscallTraceEnter *ebpf.Program `ebpf:"before_syscall_trace_enter"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.AfterGetpwnam,
		p.AfterGetpwnamR,
		p.AfterGetpwuid,
		p.AfterGetpwuidR,
		p.AfterOpenpty,
		p.AfterPamAuthenticate,
		p.BeforeGetpwnam,
		p.BeforeGetpwnamR,
		p.BeforeGetpwuid,
		p.BeforeGetpwuidR,
		p.BeforePamAuthenticate,
		p.BeforeSyscallTraceEnter,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
